module.exports = {
  apps: [
    {
      name: 'ice4-oct-web-pc',
      script: './server/index.js',
      error_file: '/app/ice4/zinoct-dev/logs/pc/error.log',
      out_file: '/app/ice4/zinoct-dev/logs/pc/out.log',
      watch: false,
      node_args: ' --max_old_space_size=2048',
      args: 'start',
      instances : 2,
      exec_mode: 'cluster',
      max_memory_restart: '1536M',
      wait_ready: true,
      listen_timeout: 50000,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '9080',
        COLLECTION: 'src/plugins/collections/common.collection.js',
        CONFIG_LEVEL: 'prd',
      },
      env_loc: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '8000',
        COLLECTION: 'src/plugins/collections/common.collection.js',
        CONFIG_LEVEL: 'loc',
      },
      env_dev: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '9081',
        COLLECTION: 'src/plugins/collections/common.collection.js',
        CONFIG_LEVEL: 'dev',
      },
      env_stg: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '9081',
        COLLECTION: 'src/plugins/collections/common.collection.js',
        CONFIG_LEVEL: 'stg',
      },
      env_prd: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '9081',
        COLLECTION: 'src/plugins/collections/common.collection.js',
        CONFIG_LEVEL: 'prd',
      },
    },
  ],
}
